### ISSUE TITLE
vtt captions not showing as video overlay

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif-visualizer#29]
### Bug Description

As the title goes, vtt files are rendered as plain text files in the relevant "tab", but never show up as overlay in the `<video>` player panel. (I can see the player recognizes the existence of CC track). 
<img width="509" alt="Screenshot 2023-08-27 at 15 54 19" src="https://github.com/clamsproject/mmif-visualizer/assets/9062727/506e3bfc-4981-4190-8233-6398bac0d014">

### Reproduction steps

Load a MMIF with ASR results and see if vtt captions show up in the video player.

**Comment by haydenmccormick** [comment]
It looks like it was an issue with the VTT formatting - fixed with 4edb59c
