### ISSUE TITLE
Adapt to MMIF version spec-0.2.1

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif-visualizer#3]

**Comment by marcverhagen** [comment]
Some things remain to be done:

- Find the TextDocument created by Kaldi and use that instead of the transcript in the documents list.
- Find the alignments using the new scheme with TimeFrame, Token and Alignment types (it now still uses the old alignments of type "vanilla-forced-alignment".

Hard is how we want to deal with the named entities from the set of TextDocument created by Tesseract and that the NER then ran over. My first hunch is to take all those documents and glue them together. I would like to change the module so it is a bit more view-centric.

**Comment by keighrim** [comment]
For the second point, a new method [`get_alignments`](https://github.com/clamsproject/mmif/blob/master/mmif-python/mmif/serialize/mmif.py#L259) in `mmif-python 0.2.2` can be helpful.

**Comment by keighrim** [comment]
This must have been fixed via #9 and #10. Or with the new work started by Hayden, this issue might be no longer relevant. @marcverhagen can you confirm?

**Comment by marcverhagen** [comment]
Maybe, I did notice a comment saying that I did not use `get_alignments` because it caused errors. SO I need to revisit this.

**Comment by marcverhagen** [comment]
Yes, this can be closed. The some-things-remaining-to-be-done were done.
