### ISSUE TITLE
Image found when running a local server

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif-visualizer#7]
When you start the visualization server without using a Docker container and without changing the `static/data` symbolic link, you will get into trouble when you have no local `/data` directory with all the multimodal data. And this is exactly what happens when you try visualize `input/kaldi-spacy.json`:

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/marc/Desktop/projects/clams/code/clamsproject/apps/mmif-visualizer/static/data/text/cpb-aacip-507-z31ng4hp5t.part.trn'
```

But if you visualize `input/image-example.json` the server does find the file. This is obviously not a problem, but I would like to understand why this happens.

**Comment by marcverhagen** [comment]
The above happened on my iMac at home, on my laptop it consistently fails with the error above.

**Comment by keighrim** [comment]
Yeah, it doesn't make sense to me, and you're probably right about the browser cache. This issue seems to be ready to go then.
